### ISSUE TITLE
ERROR TypeError: Cannot read property 'slickCurrentSlide' of undefined

### ISSUE THREAD

**Issue by rsach** [leo6104/ngx-slick-carousel#2]
https://github.com/leo6104/ngx-slick-carousel/blob/b66c6607e1e5941c95a78c31ba0f52fe8a17a033/src/slick.component.ts#L78

this line is creating a problem keep it after this line 
https://github.com/leo6104/ngx-slick-carousel/blob/b66c6607e1e5941c95a78c31ba0f52fe8a17a033/src/slick.component.ts#L88

AppComponent.html:8 ERROR TypeError: Cannot read property 'slickCurrentSlide' of undefined
    at w.fn.init.i.fn.slick (slick.min.js:1)
    at HTMLElement.<anonymous> (ngx-slick-carousel.js:30)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.y.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at HTMLElement.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
    at w.fn.init.trigger (jquery.min.js:2)
    at Object.e.init (slick.min.js:1)
View_AppComponent_1 @ AppComponent.html:8
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:12166
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1647
(anonymous) @ core.js:5093
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:4021
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:5093
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent @ core.js:5136
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap @ core.js:5042
(anonymous) @ core.js:4796
push../node_modules/@angular/core/fesm5/core.js.PlatformRef._moduleDoBootstrap @ core.js:4796
(anonymous) @ core.js:4733
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4062
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4053
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:4791
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:76
0 @ main.ts:12
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1

**Comment by denshush2** [comment]
same problem

**Comment by leo6104** [comment]
@rsach @denshush2  I publish new version for this issue. try 0.2.9 version.
