### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by Ivan-Perez** [leo6104/ngx-slick-carousel#26]
Hello!

I'm trying to upgrade my project to Angular 8, but unfortunately I can't because this module seems to use an old dependency Angular 8 is not compatible with.

To update to Angular 8, I'm using `ng update @angular/cli @angular/core` as the [Angular Update Guide](https://update.angular.io/#7.2:8.0) says. But when I run the command I get:

```
Package "ngx-slick-carousel" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.9.1").
Incompatible peer dependencies found. See above.
[ERROR]
```

Maybe updating the package.json of this module would suffice, but I don't know if doing that would remove support for previous Angular versions.

Thanks!

**Comment by GunnarHolwerda** [comment]
@leo6104 do you have an idea when you will have time to review the PR to upgrade to Angular 8? :smile:

**Comment by leo6104** [comment]
Thanks! Please check 0.4.5
