### ISSUE TITLE
cannot read property 'slick' of undefined

### ISSUE THREAD

**Issue by DmitriyTretyakov** [leo6104/ngx-slick-carousel#3]
Hello, thanks for your module.

When i try to serve my site with ssr i have error: 'cannot read property 'slick' of undefined';

I google it and found solution: comment strings "_this.$instance.slick('unslick');" in files. I think it's bug and ask you to fix it. Thanks 👍

**Comment by leo6104** [comment]
@DmitriyTretyakov Oh that's a good point. In this case, ngx-slick-carousel never call `addSlide` because of `isPlatformBrowser` condition. I fix-up these issue with `$instance` check condition.
Please try 0.3.2 :)

**Comment by DmitriyTretyakov** [comment]
All good, thanks
