### ISSUE TITLE
Metadata version mismatch for module ngx-slick-carousel.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by qbessi** [leo6104/ngx-slick-carousel#30]
Hello,

Great work on this; it's prefect for my needs.

I'm not able to upgrade to version 4 because of the size of the project is there anything else I can do to get this module to work?

This is the error i see on build:
**Metadata version mismatch for module ngx-slick-carousel.d.ts, found version 4, expected 3**

Thank you.

**Comment by leo6104** [comment]
Sorry for limitation. There is no way to support 4 version. 

If you really want to use this library code, please copy https://github.com/leo6104/ngx-slick-carousel/blob/master/src/slick.component.ts file into your project directly.
