### ISSUE TITLE
Please update version restrictions to support angular 10

### ISSUE THREAD

**Issue by talamaska** [leo6104/ngx-slick-carousel#67]
npm WARN ngx-slick-carousel@0.5.1 requires a peer of @angular/core@^7.0.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-slick-carousel@0.5.1 requires a peer of @angular/common@^7.0.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-slick-carousel@0.5.1 requires a peer of @angular/forms@^7.0.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Ivan-Perez** [comment]
And so for Angular 11.

**Comment by sukant16** [comment]
+1

**Comment by UnChallenged** [comment]
need support for angular 11+

**Comment by dunghoang103** [comment]
+1

**Comment by dharmeshds** [comment]
Is this library maintained? Still no support for Angular 11?

**Comment by UnChallenged** [comment]
I guess its no longer maintained

**Comment by leo6104** [comment]
Please use 0.6.0

**Comment by talamaska** [comment]
I see you update to support even angular 13. One thing you should also do is to ditch tslint an replace with eslint as tslint is deprecated above angular 11
