### ISSUE TITLE
Angular 10+ support

### ISSUE THREAD

**Issue by KayDash87** [leo6104/ngx-slick-carousel#76]
Hi, can update the "npm install" release version to support Angular 10+?

**Comment by michael-aquilina** [comment]
There seems to have been a commit that solved this. Can you maybe check your issue was solved? #73

**Comment by vsridhars** [comment]
Well, the issue does not seem to have resolved. 

The commit is reflecting in the package-lock in master

However no build has happened.
The last version on npmjs.com shows a 1-year older timestamp for 0.5.1

If I do a build on an Angular 12 project including the 0.5.1 version, I get the following:
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^7.0.0 || ^8.0.0 || ^9.0.0" from ngx-slick-carousel@0.5.1
npm ERR! node_modules/ngx-slick-carousel
npm ERR!   ngx-slick-carousel@"0.5.1" from the root project

**Comment by leo6104** [comment]
Please use 0.6.0
