### ISSUE TITLE
has no exported member 'ɵɵInjectorDeclaration' on upgrading to 0.6.0 ver

### ISSUE THREAD

**Issue by DongnutLa** [leo6104/ngx-slick-carousel#92]
Have many issues upgrading to 0.6.0. Is it about Angular version? Mine is 9.1.9

...node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration
...node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration
...node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration
...node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration

**Comment by leo6104** [comment]
I think you should use 0.5.x version. 

We use angular 13 for 0.6.0 and it doesn't compatible with angular 9.1.9.

**Comment by RBFraphael** [comment]
I'm facing this problem too... I'm using Angular 10, and even 0.5.X and latest (0.6) aren't working... 0.5 doesn't even install, and 0.6 is giving me these errors.
